version: "3"

services:
  bitcoind:
    environment:
      BITCOIN_TORCONTROL: tor:9051
      BITCOIN_EXTRA_ARGS: |
        onion=tor:9050
    volumes:
    - "tor_datadir:/home/tor/.tor"
    links:
    - tor

  tor:
    image: btcpayserver/tor:0.3.5.8
    environment:
      TOR_PASSWORD: btcpayserver
      TOR_EXTRA_ARGS: |
        CookieAuthentication 1
    expose:
      - "9050" # SOCKS
      - "9051" # Tor Control
    volumes:
      - "tor_datadir:/home/tor/.tor"

  clightning_bitcoin:
    environment:
      LIGHTNINGD_OPT: |
        tor-service-password=btcpayserver
        proxy=tor:9050
        addr=autotor:tor:9051
    links:
      - tor

  lnd_bitcoin:
    environment:
      LND_EXTRA_ARGS: |
        tor.active=1
        tor.v3=1
        tor.socks=tor:9050
        tor.control=tor:9051
    links:
      - tor
    volumes:
      - "tor_datadir:/home/tor/.tor"
volumes:
    tor_datadir:
